### ISSUE TITLE
Plantillas HTML 

### ISSUE THREAD

**Issue by jvegaf** [jvegaf/LagunaLink-be#29]
Necesitamos un sistema de plantillas para envio de correos

Mustache?

**Comment by jvegaf** [comment]
Handlebars o Mustache

**Comment by manubravo** [comment]
Propongo ECT, porque según he investigado es el motor de plantillas más veloz que existe, además que se integra muy bien con NodeJS y también con el Framework Express

**Comment by jvegaf** [comment]
Buena aportacion @manubravo !!! Le pegare un ojo en cuanto tenga un ratejo
